pipeline:
  mode: "FULL"
  last_run_time: "2024-12-02 00:00:00"

database:
  host: "localhost"
  port: 5432
  dbname: "dq_db"
  user: "postgres"
  password: postgres"

cost:
  cost_per_second: 0.0001
  cost_per_mb: 0.00005
